# Generated by Django 5.0.7 on 2024-07-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
