# Generated by Django 5.0.7 on 2024-07-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog_App', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default='No content')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(default='Anonymous', max_length=150)),
            ],
        ),
    ]
